name: Check
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install

      - name: ESLint
        run: pnpm eslint . --output-file eslint.report.json --format json
      - name: Annotate ESLint
        if: always()
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: eslint.report.json
          check-name: ESLint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install

      - name: Prettier
        run: pnpm prettier . --check
