name: Check
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci

      - name: ESLint
        run: npm run eslint . -- --output-file eslint.report.json --format json
      - name: Annotate ESLint
        if: always()
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: eslint.report.json
          check-name: ESLint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci

      - name: Prettier
        run: npm run prettier -- --check
