name: Push
on:
  push:
    branches:
      - main

jobs:
  latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run tsc

      - name: Push to latest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest
          git rm -r --cached .
          git add -f package.json src target tsconfig.json
          git commit -m "latest"
          git push -f origin latest
